version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: node-build  
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    restart: always

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: spring-boot-build  
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
